cp -r ./dataset/CWE78_OS_Command_Injection  ./sat_tools_dataset/
cp -r ./dataset/CWE126_Buffer_Overread ./sat_tools_dataset/
cp -r ./dataset/CWE134_Uncontrolled_Format_String ./sat_tools_dataset/
cp -r ./dataset/CWE190_Integer_Overflow ./sat_tools_dataset/
cp -r ./dataset/CWE195_Signed_to_Unsigned_Conversion_Error ./sat_tools_dataset/
cp -r ./dataset/CWE197_Numeric_Truncation_Error ./sat_tools_dataset/
cp -r ./dataset/CWE252_Unchecked_Return_Value ./sat_tools_dataset/
cp -r ./dataset/CWE369_Divide_by_Zero ./sat_tools_dataset/
cp -r ./dataset/CWE401_Memory_Leak ./sat_tools_dataset/
cp -r ./dataset/CWE404_Improper_Resource_Shutdown ./sat_tools_dataset/
cp -r ./dataset/CWE415_Double_Free ./sat_tools_dataset/
cp -r ./dataset/CWE416_Use_After_Free ./sat_tools_dataset/
cp -r ./dataset/CWE457_Use_of_Uninitialized_Variable ./sat_tools_dataset/
cp -r ./dataset/CWE467_Use_of_sizeof_on_Pointer_Type ./sat_tools_dataset/
cp -r ./dataset/CWE469_Use_of_Pointer_Subtraction_to_Determine_Size ./sat_tools_dataset/
cp -r ./dataset/CWE475_Undefined_Behavior_for_Input_to_API ./sat_tools_dataset/
cp -r ./dataset/CWE476_NULL_Pointer_Dereference ./sat_tools_dataset/
cp -r ./dataset/CWE561_Dead_Code ./sat_tools_dataset/
cp -r ./dataset/CWE562_Return_of_Stack_Variable_Address ./sat_tools_dataset/
cp -r ./dataset/CWE563_Unused_Variable ./sat_tools_dataset/
cp -r ./dataset/CWE571_Expression_Always_True ./sat_tools_dataset/
cp -r ./dataset/CWE587_Assignment_of_Fixed_Address_to_Pointer ./sat_tools_dataset/
cp -r ./dataset/CWE590_Free_Memory_Not_on_Heap ./sat_tools_dataset/
cp -r ./dataset/CWE665_Improper_Initialization ./sat_tools_dataset/
cp -r ./dataset/CWE676_Use_of_Potentially_Dangerous_Function ./sat_tools_dataset/
cp -r ./dataset/CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument ./sat_tools_dataset/
cp -r ./dataset/CWE690_NULL_Deref_From_Return ./sat_tools_dataset/
cp -r ./dataset/CWE758_Undefined_Behavior ./sat_tools_dataset/
cp -r ./dataset/CWE761_Free_Pointer_Not_at_Start_of_Buffer ./sat_tools_dataset/
cp -r ./dataset/CWE762_Mismatched_Memory_Management_Routines ./sat_tools_dataset/
cp -r ./dataset/CWE775_Missing_Release_of_File_Descriptor_or_Handle ./sat_tools_dataset/
cp -r ./dataset/CWE789_Uncontrolled_Mem_Alloc ./sat_tools_dataset/